-- =====================================================
--  rcore_police · modules/base/server/lib/sv-lib-map_creator.lua
--  Engineered by Eazy Fxap
--  Original: 12 lines → Cleaned: 6 lines
-- =====================================================
