
local dataTable, dataTable3, dataTable4, dataTable5, coords, dataTable2, coords2, counter2, counter3, counter
dataTable = {}
dataTable.started = false
dataTable3 = {}
dataTable4 = {}
dataTable4.handler = nil
dataTable5 = vec3
coords = -1655.19
dataTable2 = -1168.62
coords2 = 13.9190588
dataTable5 = dataTable5(coords, dataTable2, coords2)
dataTable4.coords = dataTable5
dataTable5 = vec3
coords = -1653.89
dataTable2 = -1167.08
coords2 = 13.9190588
dataTable5 = dataTable5(coords, dataTable2, coords2)
dataTable4.coords2 = dataTable5
dataTable5 = vec3
coords = 0.0
dataTable2 = 0.0
coords2 = 320.0
dataTable5 = dataTable5(coords, dataTable2, coords2)
dataTable4.rotation = dataTable5
dataTable5 = {}
dataTable5.x = 1.32
dataTable5.y = 1.32
dataTable5.movetype = "minus"
dataTable5.movecurrentdata1 = 0.0
dataTable5.movecurrentdata2 = 0.0
dataTable4.movedata = dataTable5
dataTable3[1] = dataTable4
dataTable4 = {}
dataTable4.handler = nil
dataTable5 = vec3
coords = -1662.27
dataTable2 = -1177.07
coords2 = 13.9190588
dataTable5 = dataTable5(coords, dataTable2, coords2)
dataTable4.coords = dataTable5
dataTable5 = vec3
coords = -1663.68
dataTable2 = -1178.74
coords2 = 13.9190588
dataTable5 = dataTable5(coords, dataTable2, coords2)
dataTable4.coords2 = dataTable5
dataTable5 = vec3
coords = 0.0
dataTable2 = 0.0
coords2 = 140.0
dataTable5 = dataTable5(coords, dataTable2, coords2)
dataTable4.rotation = dataTable5
dataTable5 = {}
dataTable5.x = 1.32
dataTable5.y = 1.32
dataTable5.movetype = "plus"
dataTable5.movecurrentdata1 = 0.0
dataTable5.movecurrentdata2 = 0.0
dataTable4.movedata = dataTable5
dataTable3[2] = dataTable4
dataTable.covers = dataTable3
dataTable3 = {}
dataTable4 = {}
dataTable5 = {}
dataTable5.handler = nil
coords = vector3
dataTable2 = 0.0
coords2 = -2.913
counter2 = -0.71
coords = coords(dataTable2, coords2, counter2)
dataTable5.coords = coords
coords = vector3
dataTable2 = 0.0
coords2 = 0.0
coords2 = -coords2
counter2 = 0.0
coords = coords(dataTable2, coords2, counter2)
dataTable5.rotation = coords
dataTable4.seatdata = dataTable5
dataTable5 = {}
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -1.126
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -1.142
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[1] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.03
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.043
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[2] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.935
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.945
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[3] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -3.832
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -3.846
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[4] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -4.734
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -4.749
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[5] = coords
dataTable4.seats = dataTable5
dataTable3[1] = dataTable4
dataTable4 = {}
dataTable5 = {}
dataTable5.handler = nil
coords = vector3
dataTable2 = 2.525
coords2 = -1.453
counter2 = -0.71
coords = coords(dataTable2, coords2, counter2)
dataTable5.coords = coords
coords = vector3
dataTable2 = 0.0
coords2 = 0.0
coords2 = -coords2
counter2 = 60.0
coords = coords(dataTable2, coords2, counter2)
dataTable5.rotation = coords
dataTable4.seatdata = dataTable5
dataTable5 = {}
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -1.126
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -1.142
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[1] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.03
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.043
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[2] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.935
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.945
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[3] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -3.832
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -3.846
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[4] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -4.734
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -4.749
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[5] = coords
dataTable4.seats = dataTable5
dataTable3[2] = dataTable4
dataTable4 = {}
dataTable5 = {}
dataTable5.handler = nil
coords = vector3
dataTable2 = 2.523
coords2 = 1.455
counter2 = -0.71
coords = coords(dataTable2, coords2, counter2)
dataTable5.coords = coords
coords = vector3
dataTable2 = 0.0
coords2 = 0.0
coords2 = -coords2
counter2 = 120.0
coords = coords(dataTable2, coords2, counter2)
dataTable5.rotation = coords
dataTable4.seatdata = dataTable5
dataTable5 = {}
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -1.126
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -1.142
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[1] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.03
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.043
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[2] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.935
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.945
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[3] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -3.832
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -3.846
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[4] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -4.734
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -4.749
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[5] = coords
dataTable4.seats = dataTable5
dataTable3[3] = dataTable4
dataTable4 = {}
dataTable5 = {}
dataTable5.handler = nil
coords = vector3
dataTable2 = 0.0
coords2 = 2.913
counter2 = -0.71
coords = coords(dataTable2, coords2, counter2)
dataTable5.coords = coords
coords = vector3
dataTable2 = 0.0
coords2 = 0.0
coords2 = -coords2
counter2 = -180.0
coords = coords(dataTable2, coords2, counter2)
dataTable5.rotation = coords
dataTable4.seatdata = dataTable5
dataTable5 = {}
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -1.126
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -1.142
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[1] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.03
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.043
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[2] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.935
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.945
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[3] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -3.832
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -3.846
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[4] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -4.734
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -4.749
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[5] = coords
dataTable4.seats = dataTable5
dataTable3[4] = dataTable4
dataTable4 = {}
dataTable5 = {}
dataTable5.handler = nil
coords = vector3
dataTable2 = -2.521
coords2 = 1.46
counter2 = -0.71
coords = coords(dataTable2, coords2, counter2)
dataTable5.coords = coords
coords = vector3
dataTable2 = 0.0
coords2 = 0.0
coords2 = -coords2
counter2 = -120.0
coords = coords(dataTable2, coords2, counter2)
dataTable5.rotation = coords
dataTable4.seatdata = dataTable5
dataTable5 = {}
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -1.126
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -1.142
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[1] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.03
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.043
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[2] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.935
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.945
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[3] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -3.832
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -3.846
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[4] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -4.734
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -4.749
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[5] = coords
dataTable4.seats = dataTable5
dataTable3[5] = dataTable4
dataTable4 = {}
dataTable5 = {}
dataTable5.handler = nil
coords = vector3
dataTable2 = -2.522
coords2 = -1.457
counter2 = -0.71
coords = coords(dataTable2, coords2, counter2)
dataTable5.coords = coords
coords = vector3
dataTable2 = 0.0
coords2 = 0.0
coords2 = -coords2
counter2 = -60.0
coords = coords(dataTable2, coords2, counter2)
dataTable5.rotation = coords
dataTable4.seatdata = dataTable5
dataTable5 = {}
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -1.126
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -1.142
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[1] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.03
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.043
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[2] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -2.935
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -2.945
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[3] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -3.832
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -3.846
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[4] = coords
coords = {}
coords.taken = false
coords.takenplayerid = nil
dataTable2 = {}
coords2 = vec3
counter2 = -0.033
counter3 = -4.734
counter = -0.793
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vec3
counter2 = 0.0
counter3 = 0.0
counter = -86.349998
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.offsets = dataTable2
dataTable2 = {}
dataTable2.handler = nil
coords2 = vector3
counter2 = -0.563
counter3 = -4.749
counter = -0.023
coords2 = coords2(counter2, counter3, counter)
dataTable2.coords = coords2
coords2 = vector3
counter2 = 0.0
counter3 = 0.0
counter3 = -counter3
counter = 0.0
coords2 = coords2(counter2, counter3, counter)
dataTable2.rotation = coords2
coords.cagedata = dataTable2
dataTable5[5] = coords
dataTable4.seats = dataTable5
dataTable3[6] = dataTable4
dataTable.cabins = dataTable3
spinridehandler = dataTable
dataTable = GlobalState
dataTable["attraction15 - phase"] = 0
dataTable = GlobalState
dataTable["attraction15 - ridedata1 - 1"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata1 - 2"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata2 - 1"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata2 - 2"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata1"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata2"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata3"] = 0.0
dataTable = GlobalState
dataTable["attraction15 - ridedata4"] = -90.0
dataTable = GlobalState
dataTable["attraction15 - speeddata1"] = 0.01
dataTable = GlobalState
dataTable["attraction15 - speeddata2"] = 0.1
dataTable = GlobalState
dataTable["attraction15 - speeddata3"] = 0.25
dataTable = GlobalState
dataTable["attraction15 - speeddata4"] = 0.25
dataTable = GlobalState
dataTable["attraction15 - speeddata5"] = 1.0
dataTable = GlobalState
dataTable["attraction15 - riderotatestop1"] = 1
dataTable = GlobalState
dataTable["attraction15 - riderotatestop2"] = 1
dataTable = GlobalState
dataTable["attraction15 - synchdata"] = 1

function dataTable()
    local isEnabled10, isEnabled6, isEnabled8, condition, strValue4, isEnabled9, strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4, strValue8, counter5, strValue6, value, isEnabled3, strValue2, isEnabled5, strValue7, var2, strValue3, value2, func, strValue, var22, isEnabled2, isDisabled, isDisabled2, var23
    isEnabled10 = spinridehandler
    isEnabled10.started = true
    isEnabled10 = true
    isEnabled6 = ipairs
    isEnabled8 = spinridehandler
    isEnabled8 = isEnabled8.cabins
    isEnabled6, isEnabled8, condition, strValue4 = isEnabled6(isEnabled8)
    for isEnabled9, strValue5 in isEnabled6, isEnabled8, condition, strValue4 do
        isEnabled7 = ipairs
        isEnabled11 = strValue5.seats
        isEnabled7, isEnabled11, isEnabled, isEnabled4 = isEnabled7(isEnabled11)
        for counter4, strValue8 in isEnabled7, isEnabled11, isEnabled, isEnabled4 do
            counter5 = strValue8.taken
            if true == counter5 then
                counter5 = TriggerClientEvent
                strValue6 = "rtx_themepark:SpinRide:SynchronizeSeat"
                value = -1
                isEnabled3 = isEnabled9
                strValue2 = counter4
                isEnabled5 = true
                strValue7 = strValue8.takenplayerid
                counter5(strValue6, value, isEnabled3, strValue2, isEnabled5, strValue7)
                counter5 = TriggerClientEvent
                strValue6 = "rtx_themepark:Global:AttractionUsing"
                value = strValue8.takenplayerid
                isEnabled3 = true
                counter5(strValue6, value, isEnabled3)
            end
        end
    end
    isEnabled6 = Citizen
    isEnabled6 = isEnabled6.Wait
    isEnabled8 = 1500
    isEnabled6(isEnabled8)
    isEnabled6 = TriggerClientEvent
    isEnabled8 = "rtx_themepark:Global:MusicStartAttraction"
    condition = -1
    strValue4 = "spinride"
    isEnabled9 = math
    isEnabled9 = isEnabled9.random
    strValue5 = 1
    isEnabled7 = Config
    isEnabled7 = isEnabled7.AttractionsMusic
    isEnabled7 = isEnabled7.spinride
    isEnabled7 = isEnabled7.playlist
    isEnabled7 = #isEnabled7
    isEnabled9, strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4, strValue8, counter5, strValue6, value, isEnabled3, strValue2, isEnabled5, strValue7, var2, strValue3, value2, func, strValue, var22, isEnabled2, isDisabled, isDisabled2, var23 = isEnabled9(strValue5, isEnabled7)
    isEnabled6(isEnabled8, condition, strValue4, isEnabled9, strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4, strValue8, counter5, strValue6, value, isEnabled3, strValue2, isEnabled5, strValue7, var2, strValue3, value2, func, strValue, var22, isEnabled2, isDisabled, isDisabled2, var23)
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - phase"] = 1
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata1 - 1"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata1 - 2"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata2 - 1"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata2 - 2"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata1"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata2"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata3"] = 0.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - ridedata4"] = -90.0
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - speeddata1"] = 0.01
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - speeddata2"] = 0.1
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - speeddata3"] = 0.25
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - speeddata4"] = 0.25
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - speeddata5"] = 0.5
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - riderotatestop1"] = 1
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - riderotatestop2"] = 1
    isEnabled6 = GlobalState
    isEnabled6["attraction15 - synchdata"] = 1
    isEnabled6 = true
    while isEnabled6 do
        isEnabled8 = Citizen
        isEnabled8 = isEnabled8.Wait
        condition = 20
        isEnabled8(condition)
        isEnabled8 = GlobalState
        isEnabled8 = isEnabled8["attraction15 - ridedata4"]
        if isEnabled8 < 0.0 then
            isEnabled8 = GlobalState
            condition = GlobalState
            condition = condition["attraction15 - ridedata4"]
            strValue4 = GlobalState
            strValue4 = strValue4["attraction15 - speeddata5"]
            condition = condition + strValue4
            isEnabled8["attraction15 - ridedata4"] = condition
        else
            isEnabled6 = false
        end
        isEnabled8 = GlobalState
        condition = GlobalState
        condition = condition["attraction15 - synchdata"]
        condition = condition + 1
        isEnabled8["attraction15 - synchdata"] = condition
    end
    isEnabled8 = GlobalState
    isEnabled8["attraction15 - phase"] = 2
    isEnabled8 = true
    while isEnabled8 do
        condition = Citizen
        condition = condition.Wait
        strValue4 = 20
        condition(strValue4)
        isEnabled8 = false
        condition = GlobalState
        condition = condition["attraction15 - ridedata1"]
        condition = tonumber(condition) or 0.0
        if condition < 10.0 then
            condition = GlobalState
            strValue4 = GlobalState
            strValue4 = strValue4["attraction15 - ridedata1"]
            strValue4 = tonumber(strValue4) or 0.0
            isEnabled9 = GlobalState
            isEnabled9 = isEnabled9["attraction15 - speeddata2"]
            isEnabled9 = tonumber(isEnabled9) or 0.0
            strValue4 = strValue4 + isEnabled9
            condition["attraction15 - ridedata1"] = strValue4
            isEnabled8 = true
        end
        condition = ipairs
        strValue4 = spinridehandler
        strValue4 = strValue4.covers
        condition, strValue4, isEnabled9, strValue5 = condition(strValue4)
        for isEnabled7, isEnabled11 in condition, strValue4, isEnabled9, strValue5 do
            isEnabled = GlobalState
            isEnabled4 = "attraction15 - ridedata"
            counter4 = isEnabled7
            strValue8 = "-1"
            isEnabled4 = isEnabled4 .. counter4 .. strValue8
            isEnabled = isEnabled[isEnabled4]
            isEnabled4 = isEnabled11.movedata
            isEnabled4 = isEnabled4.x
            isEnabled = tonumber(isEnabled) or 0.0
            isEnabled4 = tonumber(isEnabled4) or 0.0
            if isEnabled < isEnabled4 then
                isEnabled = GlobalState
                isEnabled4 = "attraction15 - ridedata"
                counter4 = isEnabled7
                strValue8 = "-1"
                isEnabled4 = isEnabled4 .. counter4 .. strValue8
                counter4 = GlobalState
                strValue8 = "attraction15 - ridedata"
                counter5 = isEnabled7
                strValue6 = "-1"
                strValue8 = strValue8 .. counter5 .. strValue6
                counter4 = counter4[strValue8]
                strValue8 = GlobalState
                strValue8 = strValue8["attraction15 - speeddata1"]
                counter4 = tonumber(counter4) or 0.0
                strValue8 = tonumber(strValue8) or 0.0
                counter4 = counter4 + strValue8
                isEnabled[isEnabled4] = counter4
                isEnabled8 = true
            end
            isEnabled = GlobalState
            isEnabled4 = "attraction15 - ridedata"
            counter4 = isEnabled7
            strValue8 = "-2"
            isEnabled4 = isEnabled4 .. counter4 .. strValue8
            isEnabled = isEnabled[isEnabled4]
            isEnabled4 = isEnabled11.movedata
            isEnabled4 = isEnabled4.y
            isEnabled = tonumber(isEnabled) or 0.0
            isEnabled4 = tonumber(isEnabled4) or 0.0
            if isEnabled < isEnabled4 then
                isEnabled = GlobalState
                isEnabled4 = "attraction15 - ridedata"
                counter4 = isEnabled7
                strValue8 = "-2"
                isEnabled4 = isEnabled4 .. counter4 .. strValue8
                counter4 = GlobalState
                strValue8 = "attraction15 - ridedata"
                counter5 = isEnabled7
                strValue6 = "-2"
                strValue8 = strValue8 .. counter5 .. strValue6
                counter4 = counter4[strValue8]
                strValue8 = GlobalState
                strValue8 = strValue8["attraction15 - speeddata1"]
                counter4 = tonumber(counter4) or 0.0
                strValue8 = tonumber(strValue8) or 0.0
                counter4 = counter4 + strValue8
                isEnabled[isEnabled4] = counter4
                isEnabled8 = true
            end
        end
        condition = GlobalState
        strValue4 = GlobalState
        strValue4 = strValue4["attraction15 - synchdata"]
        strValue4 = strValue4 + 1
        condition["attraction15 - synchdata"] = strValue4
    end
    condition = GlobalState
    condition["attraction15 - phase"] = 3
    condition = Config
    condition = condition.AttractionsSettings
    condition = condition.spinride
    condition = condition.attractiontime
    condition = condition * 1000
    strValue4 = GetGameTimer
    strValue4 = strValue4()
    strValue4 = strValue4 + condition
    isEnabled9 = true
    strValue5 = GetGameTimer
    strValue5 = strValue5()
    while isEnabled9 do
        isEnabled7 = Citizen
        isEnabled7 = isEnabled7.Wait
        isEnabled11 = 20
        isEnabled7(isEnabled11)
        isEnabled7 = GetGameTimer
        isEnabled7 = isEnabled7()
        isEnabled11 = Config
        isEnabled11 = isEnabled11.AttractionsSettings
        isEnabled11 = isEnabled11.spinride
        isEnabled11 = isEnabled11.speedmodifier
        isEnabled11 = 0.25 * isEnabled11
        isEnabled = strValue5 + 20000
        if isEnabled7 > isEnabled then
            isEnabled = Config
            isEnabled = isEnabled.AttractionsSettings
            isEnabled = isEnabled.spinride
            isEnabled = isEnabled.speedmodifier
            isEnabled11 = 4.0 * isEnabled
        else
            isEnabled = strValue5 + 18000
            if isEnabled7 > isEnabled then
                isEnabled = Config
                isEnabled = isEnabled.AttractionsSettings
                isEnabled = isEnabled.spinride
                isEnabled = isEnabled.speedmodifier
                isEnabled11 = 3.5 * isEnabled
            else
                isEnabled = strValue5 + 16000
                if isEnabled7 > isEnabled then
                    isEnabled = Config
                    isEnabled = isEnabled.AttractionsSettings
                    isEnabled = isEnabled.spinride
                    isEnabled = isEnabled.speedmodifier
                    isEnabled11 = 3.0 * isEnabled
                else
                    isEnabled = strValue5 + 15000
                    if isEnabled7 > isEnabled then
                        isEnabled = Config
                        isEnabled = isEnabled.AttractionsSettings
                        isEnabled = isEnabled.spinride
                        isEnabled = isEnabled.speedmodifier
                        isEnabled11 = 2.5 * isEnabled
                    else
                        isEnabled = strValue5 + 12000
                        if isEnabled7 > isEnabled then
                            isEnabled = Config
                            isEnabled = isEnabled.AttractionsSettings
                            isEnabled = isEnabled.spinride
                            isEnabled = isEnabled.speedmodifier
                            isEnabled11 = 2.0 * isEnabled
                        else
                            isEnabled = strValue5 + 10000
                            if isEnabled7 > isEnabled then
                                isEnabled = Config
                                isEnabled = isEnabled.AttractionsSettings
                                isEnabled = isEnabled.spinride
                                isEnabled = isEnabled.speedmodifier
                                isEnabled11 = 1.5 * isEnabled
                            else
                                isEnabled = strValue5 + 8000
                                if isEnabled7 > isEnabled then
                                    isEnabled = Config
                                    isEnabled = isEnabled.AttractionsSettings
                                    isEnabled = isEnabled.spinride
                                    isEnabled = isEnabled.speedmodifier
                                    isEnabled11 = 1.0 * isEnabled
                                else
                                    isEnabled = strValue5 + 6000
                                    if isEnabled7 > isEnabled then
                                        isEnabled = Config
                                        isEnabled = isEnabled.AttractionsSettings
                                        isEnabled = isEnabled.spinride
                                        isEnabled = isEnabled.speedmodifier
                                        isEnabled11 = 0.75 * isEnabled
                                    else
                                        isEnabled = strValue5 + 4000
                                        if isEnabled7 > isEnabled then
                                            isEnabled = Config
                                            isEnabled = isEnabled.AttractionsSettings
                                            isEnabled = isEnabled.spinride
                                            isEnabled = isEnabled.speedmodifier
                                            isEnabled11 = 0.5 * isEnabled
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        isEnabled = GlobalState
        isEnabled["attraction15 - speeddata3"] = isEnabled11
        isEnabled = GlobalState
        isEnabled["attraction15 - speeddata4"] = isEnabled11
        isEnabled = GlobalState
        isEnabled = isEnabled["attraction15 - ridedata2"]
        isEnabled4 = 360.0
        if isEnabled > isEnabled4 then
            isEnabled = GlobalState
            isEnabled = isEnabled["attraction15 - ridedata2"]
            isEnabled = isEnabled - 360.0
            isEnabled4 = GlobalState
            counter4 = 0.0 + isEnabled
            counter4 = counter4 + isEnabled11
            isEnabled4["attraction15 - ridedata2"] = counter4
        else
            isEnabled = GlobalState
            isEnabled4 = GlobalState
            isEnabled4 = isEnabled4["attraction15 - ridedata2"]
            isEnabled4 = isEnabled4 + isEnabled11
            isEnabled["attraction15 - ridedata2"] = isEnabled4
        end
        isEnabled = GlobalState
        isEnabled = isEnabled["attraction15 - ridedata3"]
        isEnabled4 = 360.0
        if isEnabled > isEnabled4 then
            isEnabled = GlobalState
            isEnabled = isEnabled["attraction15 - ridedata3"]
            isEnabled = isEnabled - 360.0
            isEnabled4 = GlobalState
            counter4 = 0.0 + isEnabled
            counter4 = counter4 + isEnabled11
            isEnabled4["attraction15 - ridedata3"] = counter4
        else
            isEnabled = GlobalState
            isEnabled4 = GlobalState
            isEnabled4 = isEnabled4["attraction15 - ridedata3"]
            isEnabled4 = isEnabled4 + isEnabled11
            isEnabled["attraction15 - ridedata3"] = isEnabled4
        end
        if strValue4 < isEnabled7 then
            isEnabled9 = false
        end
        isEnabled = GlobalState
        isEnabled4 = GlobalState
        isEnabled4 = isEnabled4["attraction15 - synchdata"]
        isEnabled4 = isEnabled4 + 1
        isEnabled["attraction15 - synchdata"] = isEnabled4
    end
    isEnabled7 = GlobalState
    isEnabled7["attraction15 - phase"] = 4
    isEnabled7 = true
    isEnabled11 = GetGameTimer
    isEnabled11 = isEnabled11()
    while isEnabled7 do
        isEnabled = Citizen
        isEnabled = isEnabled.Wait
        isEnabled4 = 20
        isEnabled(isEnabled4)
        isEnabled7 = false
        isEnabled = GetGameTimer
        isEnabled = isEnabled()
        isEnabled4 = Config
        isEnabled4 = isEnabled4.AttractionsSettings
        isEnabled4 = isEnabled4.spinride
        isEnabled4 = isEnabled4.speedmodifier
        isEnabled4 = 4.0 * isEnabled4
        counter4 = isEnabled11 + 20000
        if isEnabled > counter4 then
            counter4 = Config
            counter4 = counter4.AttractionsSettings
            counter4 = counter4.spinride
            counter4 = counter4.speedmodifier
            isEnabled4 = 0.25 * counter4
        else
            counter4 = isEnabled11 + 17500
            if isEnabled > counter4 then
                counter4 = Config
                counter4 = counter4.AttractionsSettings
                counter4 = counter4.spinride
                counter4 = counter4.speedmodifier
                isEnabled4 = 0.5 * counter4
            else
                counter4 = isEnabled11 + 15000
                if isEnabled > counter4 then
                    counter4 = Config
                    counter4 = counter4.AttractionsSettings
                    counter4 = counter4.spinride
                    counter4 = counter4.speedmodifier
                    isEnabled4 = 0.75 * counter4
                else
                    counter4 = isEnabled11 + 12500
                    if isEnabled > counter4 then
                        counter4 = Config
                        counter4 = counter4.AttractionsSettings
                        counter4 = counter4.spinride
                        counter4 = counter4.speedmodifier
                        isEnabled4 = 1.0 * counter4
                    else
                        counter4 = isEnabled11 + 10000
                        if isEnabled > counter4 then
                            counter4 = Config
                            counter4 = counter4.AttractionsSettings
                            counter4 = counter4.spinride
                            counter4 = counter4.speedmodifier
                            isEnabled4 = 1.5 * counter4
                        else
                            counter4 = isEnabled11 + 7500
                            if isEnabled > counter4 then
                                counter4 = Config
                                counter4 = counter4.AttractionsSettings
                                counter4 = counter4.spinride
                                counter4 = counter4.speedmodifier
                                isEnabled4 = 2.0 * counter4
                            else
                                counter4 = isEnabled11 + 5000
                                if isEnabled > counter4 then
                                    counter4 = Config
                                    counter4 = counter4.AttractionsSettings
                                    counter4 = counter4.spinride
                                    counter4 = counter4.speedmodifier
                                    isEnabled4 = 2.5 * counter4
                                else
                                    counter4 = isEnabled11 + 2500
                                    if isEnabled > counter4 then
                                        counter4 = Config
                                        counter4 = counter4.AttractionsSettings
                                        counter4 = counter4.spinride
                                        counter4 = counter4.speedmodifier
                                        isEnabled4 = 3.0 * counter4
                                    else
                                        counter4 = isEnabled11 + 1000
                                        if isEnabled > counter4 then
                                            counter4 = Config
                                            counter4 = counter4.AttractionsSettings
                                            counter4 = counter4.spinride
                                            counter4 = counter4.speedmodifier
                                            isEnabled4 = 3.5 * counter4
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        counter4 = GlobalState
        counter4["attraction15 - speeddata3"] = isEnabled4
        counter4 = GlobalState
        counter4["attraction15 - speeddata4"] = isEnabled4
        counter4 = GlobalState
        counter4 = counter4["attraction15 - ridedata2"]
        strValue8 = 360.0
        if counter4 >= strValue8 then
            counter4 = isEnabled11 + 25000
            if isEnabled > counter4 then
                counter4 = GlobalState
                counter4["attraction15 - riderotatestop1"] = 1
            else
                isEnabled7 = true
                counter4 = GlobalState
                counter4 = counter4["attraction15 - ridedata2"]
                counter4 = counter4 - 360.0
                strValue8 = GlobalState
                counter5 = 0.0 + counter4
                counter5 = counter5 + isEnabled4
                strValue8["attraction15 - ridedata2"] = counter5
            end
        else
            isEnabled7 = true
            counter4 = GlobalState
            strValue8 = GlobalState
            strValue8 = strValue8["attraction15 - ridedata2"]
            strValue8 = strValue8 + isEnabled4
            counter4["attraction15 - ridedata2"] = strValue8
        end
        counter4 = GlobalState
        counter4 = counter4["attraction15 - ridedata3"]
        strValue8 = 360.0
        if counter4 >= strValue8 then
            counter4 = isEnabled11 + 25000
            if isEnabled > counter4 then
                counter4 = GlobalState
                counter4["attraction15 - riderotatestop2"] = 1
            else
                isEnabled7 = true
                counter4 = GlobalState
                counter4 = counter4["attraction15 - ridedata3"]
                counter4 = counter4 - 360.0
                strValue8 = GlobalState
                counter5 = 0.0 + counter4
                counter5 = counter5 + isEnabled4
                strValue8["attraction15 - ridedata3"] = counter5
            end
        else
            isEnabled7 = true
            counter4 = GlobalState
            strValue8 = GlobalState
            strValue8 = strValue8["attraction15 - ridedata3"]
            strValue8 = strValue8 + isEnabled4
            counter4["attraction15 - ridedata3"] = strValue8
        end
        counter4 = GlobalState
        strValue8 = GlobalState
        strValue8 = strValue8["attraction15 - synchdata"]
        strValue8 = strValue8 + 1
        counter4["attraction15 - synchdata"] = strValue8
    end
    isEnabled = GlobalState
    isEnabled["attraction15 - phase"] = 5
    isEnabled = true
    while isEnabled do
        isEnabled4 = Citizen
        isEnabled4 = isEnabled4.Wait
        counter4 = 20
        isEnabled4(counter4)
        isEnabled = false
        isEnabled4 = GlobalState
        isEnabled4 = isEnabled4["attraction15 - ridedata1"]
        if isEnabled4 > 0.0 then
            isEnabled4 = GlobalState
            counter4 = GlobalState
            counter4 = counter4["attraction15 - ridedata1"]
            strValue8 = GlobalState
            strValue8 = strValue8["attraction15 - speeddata2"]
            counter4 = counter4 - strValue8
            isEnabled4["attraction15 - ridedata1"] = counter4
            isEnabled = true
        end
        isEnabled4 = ipairs
        counter4 = spinridehandler
        counter4 = counter4.covers
        isEnabled4, counter4, strValue8, counter5 = isEnabled4(counter4)
        for strValue6, value in isEnabled4, counter4, strValue8, counter5 do
            isEnabled3 = GlobalState
            strValue2 = "attraction15 - ridedata"
            isEnabled5 = strValue6
            strValue7 = "-1"
            strValue2 = strValue2 .. isEnabled5 .. strValue7
            isEnabled3 = isEnabled3[strValue2]
            if isEnabled3 > 0.0 then
                isEnabled3 = GlobalState
                strValue2 = "attraction15 - ridedata"
                isEnabled5 = strValue6
                strValue7 = "-1"
                strValue2 = strValue2 .. isEnabled5 .. strValue7
                isEnabled5 = GlobalState
                strValue7 = "attraction15 - ridedata"
                var2 = strValue6
                strValue3 = "-1"
                strValue7 = strValue7 .. var2 .. strValue3
                isEnabled5 = isEnabled5[strValue7]
                strValue7 = GlobalState
                strValue7 = strValue7["attraction15 - speeddata1"]
                isEnabled5 = isEnabled5 - strValue7
                isEnabled3[strValue2] = isEnabled5
                isEnabled = true
            end
            isEnabled3 = GlobalState
            strValue2 = "attraction15 - ridedata"
            isEnabled5 = strValue6
            strValue7 = "-2"
            strValue2 = strValue2 .. isEnabled5 .. strValue7
            isEnabled3 = isEnabled3[strValue2]
            if isEnabled3 > 0.0 then
                isEnabled3 = GlobalState
                strValue2 = "attraction15 - ridedata"
                isEnabled5 = strValue6
                strValue7 = "-2"
                strValue2 = strValue2 .. isEnabled5 .. strValue7
                isEnabled5 = GlobalState
                strValue7 = "attraction15 - ridedata"
                var2 = strValue6
                strValue3 = "-2"
                strValue7 = strValue7 .. var2 .. strValue3
                isEnabled5 = isEnabled5[strValue7]
                strValue7 = GlobalState
                strValue7 = strValue7["attraction15 - speeddata1"]
                isEnabled5 = isEnabled5 - strValue7
                isEnabled3[strValue2] = isEnabled5
                isEnabled = true
            end
        end
        isEnabled4 = GlobalState
        counter4 = GlobalState
        counter4 = counter4["attraction15 - synchdata"]
        counter4 = counter4 + 1
        isEnabled4["attraction15 - synchdata"] = counter4
    end
    isEnabled4 = GlobalState
    isEnabled4["attraction15 - phase"] = 6
    isEnabled4 = true
    while isEnabled4 do
        counter4 = Citizen
        counter4 = counter4.Wait
        strValue8 = 20
        counter4(strValue8)
        counter4 = GlobalState
        counter4 = counter4["attraction15 - ridedata4"]
        if counter4 > -90.0 then
            counter4 = GlobalState
            strValue8 = GlobalState
            strValue8 = strValue8["attraction15 - ridedata4"]
            counter5 = GlobalState
            counter5 = counter5["attraction15 - speeddata5"]
            strValue8 = strValue8 - counter5
            counter4["attraction15 - ridedata4"] = strValue8
        else
            isEnabled4 = false
        end
        counter4 = GlobalState
        strValue8 = GlobalState
        strValue8 = strValue8["attraction15 - synchdata"]
        strValue8 = strValue8 + 1
        counter4["attraction15 - synchdata"] = strValue8
    end
    counter4 = TriggerClientEvent
    strValue8 = "rtx_themepark:Global:MusicStopAttraction"
    counter5 = -1
    strValue6 = "spinride"
    counter4(strValue8, counter5, strValue6)
    counter4 = Citizen
    counter4 = counter4.Wait
    strValue8 = 1500
    counter4(strValue8)
    counter4 = GlobalState
    counter4["attraction15 - phase"] = 0
    counter4 = ipairs
    strValue8 = spinridehandler
    strValue8 = strValue8.cabins
    counter4, strValue8, counter5, strValue6 = counter4(strValue8)
    for value, isEnabled3 in counter4, strValue8, counter5, strValue6 do
        strValue2 = ipairs
        isEnabled5 = isEnabled3.seats
        strValue2, isEnabled5, strValue7, var2 = strValue2(isEnabled5)
        for strValue3, value2 in strValue2, isEnabled5, strValue7, var2 do
            func = value2.taken
            if true == func then
                value2.taken = false
                func = TriggerClientEvent
                strValue = "rtx_themepark:SpinRide:SynchronizeSeat"
                var22 = -1
                isEnabled2 = value
                isDisabled = strValue3
                isDisabled2 = false
                var23 = value2.takenplayerid
                func(strValue, var22, isEnabled2, isDisabled, isDisabled2, var23)
                func = TriggerClientEvent
                strValue = "rtx_themepark:SpinRide:SeatExit"
                var22 = value2.takenplayerid
                isEnabled2 = true
                func(strValue, var22, isEnabled2)
                func = TriggerClientEvent
                strValue = "rtx_themepark:Global:AttractionUsing"
                var22 = value2.takenplayerid
                isEnabled2 = false
                func(strValue, var22, isEnabled2)
                func = TriggerClientEvent
                strValue = "rtx_themepark:Global:TicketHandler"
                var22 = value2.takenplayerid
                isEnabled2 = 15
                isDisabled = false
                func(strValue, var22, isEnabled2, isDisabled)
                value2.takenplayerid = nil
            end
        end
    end
    counter4 = spinridehandler
    counter4.started = false
    counter4 = spinridehandler
    counter4.started = false
end
StartAttraction15 = dataTable
dataTable = RegisterServerEvent
dataTable3 = "rtx_themepark:SpinRide:SeatUse"
dataTable(dataTable3)
dataTable = AddEventHandler
dataTable3 = "rtx_themepark:SpinRide:SeatUse"

function dataTable4(A0_2, A1_2)
    local isEnabled8, condition, strValue4, isEnabled9, strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4
    isEnabled8 = source
    condition = themeparkattractionsopenstatus
    condition = condition[16]
    if true == condition then
        condition = themeparkdisabled
        if false == condition and nil ~= A0_2 and nil ~= A1_2 then
            condition = GlobalState
            condition = condition["attraction15 - phase"]
            if 0 == condition then
                condition = spinridehandler
                condition = condition.cabins
                condition = condition[A0_2]
                strValue4 = condition.seats
                strValue4 = strValue4[A1_2]
                isEnabled9 = strValue4.taken
                if false == isEnabled9 then
                    strValue4.taken = true
                    strValue4.takenplayerid = isEnabled8
                    isEnabled9 = TriggerClientEvent
                    strValue5 = "rtx_themepark:SpinRide:SynchronizeSeat"
                    isEnabled7 = -1
                    isEnabled11 = A0_2
                    isEnabled = A1_2
                    isEnabled4 = true
                    counter4 = strValue4.takenplayerid
                    isEnabled9(strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4)
                    isEnabled9 = TriggerClientEvent
                    strValue5 = "rtx_themepark:SpinRide:SeatData"
                    isEnabled7 = isEnabled8
                    isEnabled11 = A0_2
                    isEnabled = A1_2
                    isEnabled9(strValue5, isEnabled7, isEnabled11, isEnabled)
                    isEnabled9 = TriggerClientEvent
                    strValue5 = "rtx_themepark:Global:AttractionUsing"
                    isEnabled7 = isEnabled8
                    isEnabled11 = true
                    isEnabled9(strValue5, isEnabled7, isEnabled11)
                    isEnabled9 = spinridehandler
                    isEnabled9 = isEnabled9.started
                    if false == isEnabled9 then
                        isEnabled9 = Config
                        isEnabled9 = isEnabled9.ThemeParkControlAttractions
                        if false == isEnabled9 then
                            isEnabled9 = Wait
                            strValue5 = Config
                            strValue5 = strValue5.AttractionsSettings
                            strValue5 = strValue5.spinride
                            strValue5 = strValue5.waitforplayers
                            isEnabled9(strValue5)
                            isEnabled9 = spinridehandler
                            isEnabled9 = isEnabled9.started
                            if false == isEnabled9 then
                                isEnabled9 = spinridehandler
                                isEnabled9.started = true
                                isEnabled9 = StartAttraction15
                                isEnabled9()
                            end
                        end
                    end
                end
            end
        end
    end
end
dataTable(dataTable3, dataTable4)
dataTable = RegisterServerEvent
dataTable3 = "rtx_themepark:SpinRide:ExitAttraction"
dataTable(dataTable3)
dataTable = AddEventHandler
dataTable3 = "rtx_themepark:SpinRide:ExitAttraction"

function dataTable4(A0_2, A1_2)
    local isEnabled8, condition, strValue4, isEnabled9, strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4
    isEnabled8 = source
    if nil ~= A0_2 and nil ~= A0_2 then
        condition = spinridehandler
        condition = condition.cabins
        condition = condition[A0_2]
        strValue4 = condition.seats
        strValue4 = strValue4[A1_2]
        isEnabled9 = strValue4.taken
        if true == isEnabled9 then
            isEnabled9 = strValue4.takenplayerid
            if isEnabled9 == isEnabled8 then
                isEnabled9 = Config
                isEnabled9 = isEnabled9.ThemeParkDisableExit
                if false ~= isEnabled9 then
                    isEnabled9 = GlobalState
                    isEnabled9 = isEnabled9["attraction15 - phase"]
                    if 0 ~= isEnabled9 then
                        goto lbl_46
                    end
                end
                isEnabled9 = TriggerClientEvent
                strValue5 = "rtx_themepark:SpinRide:SynchronizeSeat"
                isEnabled7 = -1
                isEnabled11 = A0_2
                isEnabled = A1_2
                isEnabled4 = false
                counter4 = strValue4.takenplayerid
                isEnabled9(strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4)
                isEnabled9 = TriggerClientEvent
                strValue5 = "rtx_themepark:SpinRide:SeatExit"
                isEnabled7 = strValue4.takenplayerid
                isEnabled11 = false
                isEnabled9(strValue5, isEnabled7, isEnabled11)
                isEnabled9 = TriggerClientEvent
                strValue5 = "rtx_themepark:Global:AttractionUsing"
                isEnabled7 = strValue4.takenplayerid
                isEnabled11 = false
                isEnabled9(strValue5, isEnabled7, isEnabled11)
                strValue4.taken = false
                strValue4.takenplayerid = nil
                goto lbl_55
                ::lbl_46::
                isEnabled9 = TriggerClientEvent
                strValue5 = "rtx_themepark:Notify"
                isEnabled7 = isEnabled8
                isEnabled11 = Language
                isEnabled = Config
                isEnabled = isEnabled.Language
                isEnabled11 = isEnabled11[isEnabled]
                isEnabled11 = isEnabled11.inprogress
                isEnabled9(strValue5, isEnabled7, isEnabled11)
            end
        end
    end
    ::lbl_55::
end
dataTable(dataTable3, dataTable4)
dataTable = RegisterServerEvent
dataTable3 = "rtx_themepark:SpinRide:Resynch"
dataTable(dataTable3)
dataTable = AddEventHandler
dataTable3 = "rtx_themepark:SpinRide:Resynch"

function dataTable4()
    local isEnabled10, isEnabled6, isEnabled8, condition, strValue4, isEnabled9, strValue5, isEnabled7, isEnabled11, isEnabled, isEnabled4, counter4, strValue8, counter5, strValue6, value, isEnabled3, strValue2, isEnabled5, strValue7
    isEnabled10 = source
    isEnabled6 = ipairs
    isEnabled8 = praterhandler
    isEnabled8 = isEnabled8.seats
    isEnabled6, isEnabled8, condition, strValue4 = isEnabled6(isEnabled8)
    for isEnabled9, strValue5 in isEnabled6, isEnabled8, condition, strValue4 do
        isEnabled7 = ipairs
        isEnabled11 = strValue5.seats
        isEnabled7, isEnabled11, isEnabled, isEnabled4 = isEnabled7(isEnabled11)
        for counter4, strValue8 in isEnabled7, isEnabled11, isEnabled, isEnabled4 do
            counter5 = TriggerClientEvent
            strValue6 = "rtx_themepark:SpinRide:SynchronizeSeat"
            value = isEnabled10
            isEnabled3 = isEnabled9
            strValue2 = counter4
            isEnabled5 = strValue8.taken
            strValue7 = strValue8.takenplayerid
            counter5(strValue6, value, isEnabled3, strValue2, isEnabled5, strValue7)
        end
    end
    isEnabled6 = spinridehandler
    isEnabled6 = isEnabled6.started
    if true == isEnabled6 then
        isEnabled6 = TriggerClientEvent
        isEnabled8 = "rtx_themepark:SpinRide:ResynchClient"
        condition = isEnabled10
        isEnabled6(isEnabled8, condition)
    end
end
dataTable(dataTable3, dataTable4)
dataTable = AddEventHandler
dataTable3 = "rtx_themepark:SpinRide:Start"

function dataTable4()
    local isEnabled10, isEnabled6
    isEnabled10 = spinridehandler
    isEnabled10 = isEnabled10.started
    if false == isEnabled10 then
        isEnabled10 = spinridehandler
        isEnabled10.started = true
        isEnabled10 = StartAttraction15
        isEnabled10()
    end
end
dataTable(dataTable3, dataTable4)
