--[[
========================================================================================
 ██████╗ ██╗     ███████╗ █████╗ ███╗   ██╗███████╗██████╗ 
██╔════╝ ██║     ██╔════╝██╔══██╗████╗  ██║██╔════╝██╔══██╗
██║      ██║     █████╗  ███████║██╔██╗ ██║█████╗  ██║  ██║
██║      ██║     ██╔══╝  ██╔══██║██║╚██╗██║██╔══╝  ██║  ██║
╚██████╗ ███████╗███████╗██║  ██║██║ ╚████║███████╗██████╔╝
 ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚═════╝ 

                 ██████╗ ██╗   ██╗
                 ██╔══██╗╚██╗ ██╔╝
                 ██████╔╝ ╚████╔╝ 
                 ██╔══██╗  ╚██╔╝  
                 ██████╔╝   ██║   
                 ╚═════╝    ╚═╝   

██╗  ██╗ █████╗ ███████╗██╗███╗   ███╗
██║  ██║██╔══██╗╚══███╔╝██║████╗ ████║
███████║███████║  ███╔╝ ██║██╔████╔██║
██╔══██║██╔══██║ ███╔╝  ██║██║╚██╔╝██║
██║  ██║██║  ██║███████╗██║██║ ╚═╝ ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝     ╚═╝

██╗  ██╗███████╗██████╗ ██████╗ ███████╗██████╗  █████╗ 
██║  ██║██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
███████║█████╗  ██████╔╝██████╔╝█████╗  ██████╔╝███████║
██╔══██║██╔══╝  ██╔══██╗██╔══██╗██╔══╝  ██╔══██╗██╔══██║
██║  ██║███████╗██║  ██║██║  ██║███████╗██║  ██║██║  ██║
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
========================================================================================
--]]

local InputKeyStrings = {
    ["~INPUT_REPLAY_STARTPOINT~"] = "[B]",
    ["~INPUT_NEXT_CAMERA~"] = "[V]",
    ["~INPUT_LOOK_LR~"] = "[Right Stick X]",
    ["~INPUT_LOOK_UD~"] = "[Right Stick Y]",
    ["~INPUT_LOOK_UP_ONLY~"] = "[Right Stick Up]",
    ["~INPUT_LOOK_DOWN_ONLY~"] = "[Right Stick Down]",
    ["~INPUT_LOOK_LEFT_ONLY~"] = "[Right Stick Left]",
    ["~INPUT_LOOK_RIGHT_ONLY~"] = "[Right Stick Right]",
    ["~INPUT_CINEMATIC_SLOWMO~"] = "[Toggle Cinematic Slowmo]",
    ["~INPUT_SCRIPTED_FLY_UD~"] = "[Right Stick Y]",
    ["~INPUT_SCRIPTED_FLY_LR~"] = "[Right Stick X]",
    ["~INPUT_SCRIPTED_FLY_ZUP~"] = "[RT]",
    ["~INPUT_SCRIPTED_FLY_ZDOWN~"] = "[LT]",
    ["~INPUT_WEAPON_WHEEL_UD~"] = "[Right Stick Y]",
    ["~INPUT_WEAPON_WHEEL_LR~"] = "[Right Stick X]",
    ["~INPUT_WEAPON_WHEEL_NEXT~"] = "[Mouse Scroll Down]",
    ["~INPUT_WEAPON_WHEEL_PREV~"] = "[Mouse Scroll Up]",
    ["~INPUT_SELECT_NEXT_WEAPON~"] = "[Mouse Scroll Down]",
    ["~INPUT_SELECT_PREV_WEAPON~"] = "[Mouse Scroll Up]",
    ["~INPUT_SKIP_CUTSCENE~"] = "[Esc]",
    ["~INPUT_CHARACTER_WHEEL~"] = "[Left Alt]",
    ["~INPUT_MULTIPLAYER_INFO~"] = "[Z]",
    ["~INPUT_SPRINT~"] = "[Shift]",
    ["~INPUT_JUMP~"] = "[Space]",
    ["~INPUT_ENTER~"] = "[F]",
    ["~INPUT_ATTACK~"] = "[Left Mouse Button]",
    ["~INPUT_AIM~"] = "[Right Mouse Button]",
    ["~INPUT_LOOK_BEHIND~"] = "[C]",
    ["~INPUT_PHONE~"] = "[Up Arrow]",
    ["~INPUT_SPECIAL_ABILITY~"] = "[Caps Lock]",
    ["~INPUT_SPECIAL_ABILITY_SECONDARY~"] = "[B]",
    ["~INPUT_MOVE_LR~"] = "[A/D]",
    ["~INPUT_MOVE_UD~"] = "[W/S]",
    ["~INPUT_MOVE_UP_ONLY~"] = "[W]",
    ["~INPUT_MOVE_DOWN_ONLY~"] = "[S]",
    ["~INPUT_MOVE_LEFT_ONLY~"] = "[A]",
    ["~INPUT_MOVE_RIGHT_ONLY~"] = "[D]",
    ["~INPUT_DUCK~"] = "[X]",
    ["~INPUT_SELECT_WEAPON~"] = "[Tab]",
    ["~INPUT_PICKUP~"] = "[E]",
    ["~INPUT_SNIPER_ZOOM~"] = "[Mouse Scroll]",
    ["~INPUT_SNIPER_ZOOM_IN_ONLY~"] = "[Mouse Scroll Up]",
    ["~INPUT_SNIPER_ZOOM_OUT_ONLY~"] = "[Mouse Scroll Down]",
    ["~INPUT_SNIPER_ZOOM_IN_SECONDARY~"] = "[Num +]",
    ["~INPUT_SNIPER_ZOOM_OUT_SECONDARY~"] = "[Num -]",
    ["~INPUT_COVER~"] = "[Q]",
    ["~INPUT_RELOAD~"] = "[R]",
    ["~INPUT_TALK~"] = "[N]",
    ["~INPUT_DETONATE~"] = "[G]",
    ["~INPUT_HUD_SPECIAL~"] = "[Alt]",
    ["~INPUT_ARREST~"] = "[F]",
    ["~INPUT_ACCURATE_AIM~"] = "[R Mouse]",
    ["~INPUT_CONTEXT~"] = "[E]",
    ["~INPUT_CONTEXT_SECONDARY~"] = "[Q]",
    ["~INPUT_WEAPON_SPECIAL~"] = "[R]",
    ["~INPUT_WEAPON_SPECIAL_TWO~"] = "[E]",
    ["~INPUT_DIVE~"] = "[Space]",
    ["~INPUT_DROP_WEAPON~"] = "[F9]",
    ["~INPUT_DROP_AMMO~"] = "[F10]",
    ["~INPUT_THROW_GRENADE~"] = "[G]",
    ["~INPUT_VEH_MOVE_LR~"] = "[A/D]",
    ["~INPUT_VEH_MOVE_UD~"] = "[W/S]",
    ["~INPUT_VEH_MOVE_UP_ONLY~"] = "[W]",
    ["~INPUT_VEH_MOVE_DOWN_ONLY~"] = "[S]",
    ["~INPUT_VEH_MOVE_LEFT_ONLY~"] = "[A]",
    ["~INPUT_VEH_MOVE_RIGHT_ONLY~"] = "[D]",
    ["~INPUT_VEH_SPECIAL~"] = "[Shift]",
    ["~INPUT_VEH_GUN_LR~"] = "[Mouse X]",
    ["~INPUT_VEH_GUN_UD~"] = "[Mouse Y]",
    ["~INPUT_VEH_ATTACK~"] = "[Left Mouse Button]",
    ["~INPUT_VEH_ATTACK2~"] = "[Right Mouse Button]",
    ["~INPUT_VEH_ACCELERATE~"] = "[W]",
    ["~INPUT_VEH_BRAKE~"] = "[S]",
    ["~INPUT_VEH_DUCK~"] = "[X]",
    ["~INPUT_VEH_HEADLIGHT~"] = "[H]",
    ["~INPUT_VEH_EXIT~"] = "[F]",
    ["~INPUT_VEH_HANDBRAKE~"] = "[Space]",
    ["~INPUT_VEH_HOTWIRE_LEFT~"] = "[A]",
    ["~INPUT_VEH_HOTWIRE_RIGHT~"] = "[D]",
    ["~INPUT_VEH_LOOK_BEHIND~"] = "[C]",
    ["~INPUT_VEH_CIN_CAM~"] = "[R]",
    ["~INPUT_VEH_NEXT_RADIO~"] = "[=]",
    ["~INPUT_VEH_PREV_RADIO~"] = "[-]",
    ["~INPUT_VEH_NEXT_RADIO_TRACK~"] = "[>] (Right Arrow)",
    ["~INPUT_VEH_PREV_RADIO_TRACK~"] = "[<] (Left Arrow)",
    ["~INPUT_VEH_RADIO_WHEEL~"] = "[Q]",
    ["~INPUT_VEH_HORN~"] = "[E]",
    ["~INPUT_VEH_FLY_THROTTLE_UP~"] = "[W]",
    ["~INPUT_VEH_FLY_THROTTLE_DOWN~"] = "[S]",
    ["~INPUT_VEH_FLY_YAW_LEFT~"] = "[A]",
    ["~INPUT_VEH_FLY_YAW_RIGHT~"] = "[D]",
    ["~INPUT_VEH_PASSENGER_AIM~"] = "[Right Mouse Button]",
    ["~INPUT_VEH_PASSENGER_ATTACK~"] = "[Left Mouse Button]",
    ["~INPUT_VEH_SPECIAL_ABILITY_FRANKLIN~"] = "[Caps Lock]",
    ["~INPUT_VEH_STUNT_UD~"] = "[W/S]",
    ["~INPUT_VEH_CINEMATIC_UD~"] = "[Right Stick Y]",
    ["~INPUT_VEH_CINEMATIC_UP_ONLY~"] = "[Right Stick Up]",
    ["~INPUT_VEH_CINEMATIC_DOWN_ONLY~"] = "[Right Stick Down]",
    ["~INPUT_VEH_CINEMATIC_LR~"] = "[Right Stick X]",
    ["~INPUT_VEH_SELECT_NEXT_WEAPON~"] = "[Mouse Scroll Down]",
    ["~INPUT_VEH_SELECT_PREV_WEAPON~"] = "[Mouse Scroll Up]",
    ["~INPUT_VEH_ROOF~"] = "[H]",
    ["~INPUT_VEH_JUMP~"] = "[Space]",
    ["~INPUT_VEH_GRAPPLING_HOOK~"] = "[E]",
    ["~INPUT_VEH_SHUFFLE~"] = "[H]",
    ["~INPUT_VEH_DROP_PROJECTILE~"] = "[X]",
    ["~INPUT_VEH_MOUSE_CONTROL_OVERRIDE~"] = "[Mouse X/Y]",
    ["~INPUT_VEH_FLY_ROLL_LR~"] = "[A/D]",
    ["~INPUT_VEH_FLY_ROLL_LEFT_ONLY~"] = "[A]",
    ["~INPUT_VEH_FLY_ROLL_RIGHT_ONLY~"] = "[D]",
    ["~INPUT_VEH_FLY_PITCH_UD~"] = "[W/S]",
    ["~INPUT_VEH_FLY_PITCH_UP_ONLY~"] = "[W]",
    ["~INPUT_VEH_FLY_PITCH_DOWN_ONLY~"] = "[S]",
    ["~INPUT_VEH_FLY_UNDERCARRIAGE~"] = "[G]",
    ["~INPUT_VEH_FLY_ATTACK~"] = "[Left Mouse Button]",
    ["~INPUT_VEH_FLY_SELECT_NEXT_WEAPON~"] = "[Mouse Scroll Down]",
    ["~INPUT_VEH_FLY_SELECT_PREV_WEAPON~"] = "[Mouse Scroll Up]",
    ["~INPUT_VEH_FLY_SELECT_TARGET_LEFT~"] = "[A]",
    ["~INPUT_VEH_FLY_SELECT_TARGET_RIGHT~"] = "[D]",
    ["~INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE~"] = "[E]",
    ["~INPUT_VEH_FLY_DUCK~"] = "[X]",
    ["~INPUT_VEH_FLY_ATTACK_CAMERA~"] = "[Right Mouse Button]",
    ["~INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE~"] = "[Mouse X/Y]",
    ["~INPUT_VEH_SUB_TURN_LR~"] = "[A/D]",
    ["~INPUT_VEH_SUB_TURN_LEFT_ONLY~"] = "[A]",
    ["~INPUT_VEH_SUB_TURN_RIGHT_ONLY~"] = "[D]",
    ["~INPUT_VEH_SUB_PITCH_UD~"] = "[W/S]",
    ["~INPUT_VEH_SUB_PITCH_UP_ONLY~"] = "[W]",
    ["~INPUT_VEH_SUB_PITCH_DOWN_ONLY~"] = "[S]",
    ["~INPUT_VEH_SUB_THROTTLE_UP~"] = "[W]",
    ["~INPUT_VEH_SUB_THROTTLE_DOWN~"] = "[S]",
    ["~INPUT_VEH_SUB_ASCEND~"] = "[Space]",
    ["~INPUT_VEH_SUB_DESCEND~"] = "[Ctrl]",
    ["~INPUT_VEH_SUB_TURN_HARD_LEFT~"] = "[Q]",
    ["~INPUT_VEH_SUB_TURN_HARD_RIGHT~"] = "[E]",
    ["~INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE~"] = "[Mouse X/Y]",
    ["~INPUT_VEH_PUSHBIKE_PEDAL~"] = "[W]",
    ["~INPUT_VEH_PUSHBIKE_SPRINT~"] = "[Caps Lock]",
    ["~INPUT_VEH_PUSHBIKE_FRONT_BRAKE~"] = "[Q]",
    ["~INPUT_VEH_PUSHBIKE_REAR_BRAKE~"] = "[S]",
    ["~INPUT_MELEE_ATTACK_LIGHT~"] = "[R]",
    ["~INPUT_MELEE_ATTACK_HEAVY~"] = "[Q]",
    ["~INPUT_MELEE_ATTACK_ALTERNATE~"] = "[R Mouse]",
    ["~INPUT_MELEE_BLOCK~"] = "[Space]",
    ["~INPUT_PARACHUTE_DEPLOY~"] = "[F]",
    ["~INPUT_PARACHUTE_DETACH~"] = "[F]",
    ["~INPUT_PARACHUTE_TURN_LR~"] = "[A/D]",
    ["~INPUT_PARACHUTE_TURN_LEFT_ONLY~"] = "[A]",
    ["~INPUT_PARACHUTE_TURN_RIGHT_ONLY~"] = "[D]",
    ["~INPUT_PARACHUTE_PITCH_UD~"] = "[W/S]",
    ["~INPUT_PARACHUTE_PITCH_UP_ONLY~"] = "[W]",
    ["~INPUT_PARACHUTE_PITCH_DOWN_ONLY~"] = "[S]",
    ["~INPUT_PARACHUTE_BRAKE_LEFT~"] = "[Q]",
    ["~INPUT_PARACHUTE_BRAKE_RIGHT~"] = "[E]",
    ["~INPUT_PARACHUTE_SMOKE~"] = "[X]",
    ["~INPUT_PARACHUTE_PRECISION_LANDING~"] = "[Shift]",
    ["~INPUT_MAP~"] = "[P]",
    ["~INPUT_SELECT_WEAPON_UNARMED~"] = "[1]",
    ["~INPUT_SELECT_WEAPON_MELEE~"] = "[2]",
    ["~INPUT_SELECT_WEAPON_HANDGUN~"] = "[3]",
    ["~INPUT_SELECT_WEAPON_SHOTGUN~"] = "[4]",
    ["~INPUT_SELECT_WEAPON_SMG~"] = "[5]",
    ["~INPUT_SELECT_WEAPON_AUTO_RIFLE~"] = "[6]",
    ["~INPUT_SELECT_WEAPON_SNIPER~"] = "[7]",
    ["~INPUT_SELECT_WEAPON_HEAVY~"] = "[8]",
    ["~INPUT_SELECT_WEAPON_SPECIAL~"] = "[9]",
    ["~INPUT_SELECT_CHARACTER_MICHAEL~"] = "[F5]",
    ["~INPUT_SELECT_CHARACTER_FRANKLIN~"] = "[F6]",
    ["~INPUT_SELECT_CHARACTER_TREVOR~"] = "[F7]",
    ["~INPUT_SELECT_CHARACTER_MULTIPLAYER~"] = "[F8]",
    ["~INPUT_SAVE_REPLAY_CLIP~"] = "[F3]",
    ["~INPUT_SPECIAL_ABILITY_PC~"] = "[Caps Lock]",
    ["~INPUT_CELLPHONE_UP~"] = "[Up Arrow]",
    ["~INPUT_CELLPHONE_DOWN~"] = "[Down Arrow]",
    ["~INPUT_CELLPHONE_LEFT~"] = "[Left Arrow]",
    ["~INPUT_CELLPHONE_RIGHT~"] = "[Right Arrow]",
    ["~INPUT_CELLPHONE_SELECT~"] = "[Enter]",
    ["~INPUT_CELLPHONE_CANCEL~"] = "[Backspace]",
    ["~INPUT_CELLPHONE_OPTION~"] = "[Space]",
    ["~INPUT_CELLPHONE_EXTRA_OPTION~"] = "[E]",
    ["~INPUT_CELLPHONE_SCROLL_FORWARD~"] = "[Mouse Scroll Up]",
    ["~INPUT_CELLPHONE_SCROLL_BACKWARD~"] = "[Mouse Scroll Down]",
    ["~INPUT_CELLPHONE_CAMERA_FOCUS_LOCK~"] = "[L]",
    ["~INPUT_CELLPHONE_CAMERA_GRID~"] = "[G]",
    ["~INPUT_CELLPHONE_CAMERA_SELFIE~"] = "[F]",
    ["~INPUT_CELLPHONE_CAMERA_DOF~"] = "[D]",
    ["~INPUT_CELLPHONE_CAMERA_EXPRESSION~"] = "[Space]",
    ["~INPUT_FRONTEND_DOWN~"] = "[Down Arrow]",
    ["~INPUT_FRONTEND_UP~"] = "[Up Arrow]",
    ["~INPUT_FRONTEND_LEFT~"] = "[Left Arrow]",
    ["~INPUT_FRONTEND_RIGHT~"] = "[Right Arrow]",
    ["~INPUT_FRONTEND_RDOWN~"] = "[Enter]",
    ["~INPUT_FRONTEND_RUP~"] = "[Tab]",
    ["~INPUT_FRONTEND_RLEFT~"] = "[Backspace]",
    ["~INPUT_FRONTEND_RRIGHT~"] = "[Q]",
    ["~INPUT_FRONTEND_AXIS_X~"] = "[D-Pad X]",
    ["~INPUT_FRONTEND_AXIS_Y~"] = "[D-Pad Y]",
    ["~INPUT_FRONTEND_RIGHT_AXIS_X~"] = "[Right Stick X]",
    ["~INPUT_FRONTEND_RIGHT_AXIS_Y~"] = "[Right Stick Y]",
    ["~INPUT_FRONTEND_PAUSE~"] = "[P]",
    ["~INPUT_FRONTEND_PAUSE_ALTERNATE~"] = "[Esc]",
    ["~INPUT_FRONTEND_ACCEPT~"] = "[Enter]",
    ["~INPUT_FRONTEND_CANCEL~"] = "[Backspace]",
    ["~INPUT_FRONTEND_X~"] = "[E]",
    ["~INPUT_FRONTEND_Y~"] = "[Space]",
    ["~INPUT_FRONTEND_LB~"] = "[Q]",
    ["~INPUT_FRONTEND_RB~"] = "[E]",
    ["~INPUT_FRONTEND_LT~"] = "[Tab]",
    ["~INPUT_FRONTEND_RT~"] = "[Enter]",
    ["~INPUT_FRONTEND_LS~"] = "[Shift]",
    ["~INPUT_FRONTEND_RS~"] = "[Left Ctrl]",
    ["~INPUT_FRONTEND_LEADERBOARD~"] = "[Tab]",
    ["~INPUT_FRONTEND_SOCIAL_CLUB~"] = "[Home]",
    ["~INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY~"] = "[L]",
    ["~INPUT_FRONTEND_DELETE~"] = "[Del]",
    ["~INPUT_FRONTEND_ENDSCREEN_ACCEPT~"] = "[Enter]",
    ["~INPUT_FRONTEND_ENDSCREEN_EXPAND~"] = "[Space]",
    ["~INPUT_FRONTEND_SELECT~"] = "[Enter]",
    ["~INPUT_SCRIPT_LEFT_AXIS_X~"] = "[Left Stick X]",
    ["~INPUT_SCRIPT_LEFT_AXIS_Y~"] = "[Left Stick Y]",
    ["~INPUT_SCRIPT_RIGHT_AXIS_X~"] = "[Right Stick X]",
    ["~INPUT_SCRIPT_RIGHT_AXIS_Y~"] = "[Right Stick Y]",
    ["~INPUT_SCRIPT_RUP~"] = "[Right Stick Up]",
    ["~INPUT_SCRIPT_RDOWN~"] = "[Right Stick Down]",
    ["~INPUT_SCRIPT_RLEFT~"] = "[Right Stick Left]",
    ["~INPUT_SCRIPT_RRIGHT~"] = "[Right Stick Right]",
    ["~INPUT_SCRIPT_LB~"] = "[LB]",
    ["~INPUT_SCRIPT_RB~"] = "[RB]",
    ["~INPUT_SCRIPT_LT~"] = "[LT]",
    ["~INPUT_SCRIPT_RT~"] = "[RT]",
    ["~INPUT_SCRIPT_LS~"] = "[Left Stick]",
    ["~INPUT_SCRIPT_RS~"] = "[Right Stick]",
    ["~INPUT_SCRIPT_PAD_UP~"] = "[D-Pad Up]",
    ["~INPUT_SCRIPT_PAD_DOWN~"] = "[D-Pad Down]",
    ["~INPUT_SCRIPT_PAD_LEFT~"] = "[D-Pad Left]",
    ["~INPUT_SCRIPT_PAD_RIGHT~"] = "[D-Pad Right]",
    ["~INPUT_SCRIPT_SELECT~"] = "[Enter]",
    ["~INPUT_CURSOR_ACCEPT~"] = "[Left Mouse Button]",
    ["~INPUT_CURSOR_CANCEL~"] = "[Right Mouse Button]",
    ["~INPUT_CURSOR_X~"] = "[Mouse X]",
    ["~INPUT_CURSOR_Y~"] = "[Mouse Y]",
    ["~INPUT_CURSOR_SCROLL_UP~"] = "[Mouse Scroll Up]",
    ["~INPUT_CURSOR_SCROLL_DOWN~"] = "[Mouse Scroll Down]",
    ["~INPUT_ENTER_CHEAT_CODE~"] = "[~ (Tilde)]",
    ["~INPUT_INTERACTION_MENU~"] = "[M]",
    ["~INPUT_MP_TEXT_CHAT_ALL~"] = "[T]",
    ["~INPUT_MP_TEXT_CHAT_TEAM~"] = "[Y]",
    ["~INPUT_MP_TEXT_CHAT_FRIENDS~"] = "[U]",
    ["~INPUT_MP_TEXT_CHAT_CREW~"] = "[I]",
    ["~INPUT_PUSH_TO_TALK~"] = "[N]",
    ["~INPUT_CREATOR_LS~"] = "[Left Stick]",
    ["~INPUT_CREATOR_RS~"] = "[Right Stick]",
    ["~INPUT_CREATOR_LT~"] = "[LT]",
    ["~INPUT_CREATOR_RT~"] = "[RT]",
    ["~INPUT_CREATOR_MENU_TOGGLE~"] = "[Backspace]",
    ["~INPUT_CREATOR_ACCEPT~"] = "[Enter]",
    ["~INPUT_CREATOR_DELETE~"] = "[Del]",
    ["~INPUT_ATTACK2~"] = "[Right Mouse Button]",
    ["~INPUT_RAPPEL_JUMP~"] = "[Space]",
    ["~INPUT_RAPPEL_LONG_JUMP~"] = "[Shift]",
    ["~INPUT_RAPPEL_SMASH_WINDOW~"] = "[F]",
    ["~INPUT_PREV_WEAPON~"] = "[Mouse Scroll Up]",
    ["~INPUT_NEXT_WEAPON~"] = "[Mouse Scroll Down]",
    ["~INPUT_MELEE_ATTACK1~"] = "[R]",
    ["~INPUT_MELEE_ATTACK2~"] = "[Q]",
    ["~INPUT_WHISTLE~"] = "[H]",
    ["~INPUT_MOVE_LEFT~"] = "[A]",
    ["~INPUT_MOVE_RIGHT~"] = "[D]",
    ["~INPUT_MOVE_UP~"] = "[W]",
    ["~INPUT_MOVE_DOWN~"] = "[S]",
    ["~INPUT_LOOK_LEFT~"] = "[Mouse X]",
    ["~INPUT_LOOK_RIGHT~"] = "[Mouse X]",
    ["~INPUT_LOOK_UP~"] = "[Mouse Y]",
    ["~INPUT_LOOK_DOWN~"] = "[Mouse Y]",
    ["~INPUT_SNIPER_ZOOM_IN~"] = "[Mouse Scroll Up]",
    ["~INPUT_SNIPER_ZOOM_OUT~"] = "[Mouse Scroll Down]",
    ["~INPUT_SNIPER_ZOOM_IN_ALT~"] = "[Num +]",
    ["~INPUT_SNIPER_ZOOM_OUT_ALT~"] = "[Num -]",
    ["~INPUT_VEH_MOVE_LEFT~"] = "[A]",
    ["~INPUT_VEH_MOVE_RIGHT~"] = "[D]",
    ["~INPUT_VEH_MOVE_UP~"] = "[W]",
    ["~INPUT_VEH_MOVE_DOWN~"] = "[S]",
    ["~INPUT_VEH_GUN_LEFT~"] = "[Mouse X]",
    ["~INPUT_VEH_GUN_RIGHT~"] = "[Mouse X]",
    ["~INPUT_VEH_GUN_UP~"] = "[Mouse Y]",
    ["~INPUT_VEH_GUN_DOWN~"] = "[Mouse Y]",
    ["~INPUT_VEH_LOOK_LEFT~"] = "[Mouse X]",
    ["~INPUT_VEH_LOOK_RIGHT~"] = "[Mouse X]",
    ["~INPUT_REPLAY_ENDPOINT~"] = "[N]",
    ["~INPUT_REPLAY_SAVE~"] = "[F5]",
    ["~INPUT_REPLAY_CANCEL~"] = "[F6]",
    ["~INPUT_REPLAY_REWIND~"] = "[Left Arrow]",
    ["~INPUT_REPLAY_FFWD~"] = "[Right Arrow]",
    ["~INPUT_REPLAY_NEWMARKER~"] = "[M]",
    ["~INPUT_REPLAY_RECORD~"] = "[R]",
    ["~INPUT_REPLAY_SCREENSHOT~"] = "[Space]",
    ["~INPUT_REPLAY_HIDEHUD~"] = "[H]",
    ["~INPUT_REPLAY_START_STOP_RECORDING~"] = "[Q]",
    ["~INPUT_REPLAY_START_STOP_RECORDING_SECONDARY~"] = "[E]",
    ["~INPUT_SCALED_LOOK_LR~"] = "[Right Stick X]",
    ["~INPUT_SCALED_LOOK_UD~"] = "[Right Stick Y]",
    ["~INPUT_SCALED_LOOK_UP_ONLY~"] = "[Right Stick Up]",
    ["~INPUT_SCALED_LOOK_DOWN_ONLY~"] = "[Right Stick Down]",
    ["~INPUT_SCALED_LOOK_LEFT_ONLY~"] = "[Right Stick Left]",
    ["~INPUT_SCALED_LOOK_RIGHT_ONLY~"] = "[Right Stick Right]",
    ["~INPUT_REPLAY_TIMELINE_PICKUP_CLIP~"] = "[X]",
    ["~INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP~"] = "[C]",
    ["~INPUT_REPLAY_TIMELINE_PLACE_CLIP~"] = "[V]",
    ["~INPUT_REPLAY_CTRL~"] = "[Left Ctrl]",
    ["~INPUT_REPLAY_TIMELINE_SAVE~"] = "[F5]",
    ["~INPUT_REPLAY_PREVIEW~"] = "[P]",
    ["~INPUT_REPLAY_TOGGLE_TIMELINE~"] = "[T]",
    ["~INPUT_REPLAY_TIMELINE_DELETE~"] = "[Del]",
    ["~INPUT_REPLAY_TOGGLE_TIMELINE_LENGTH~"] = "[Tab]",
    ["~INPUT_REPLAY_UPDATE_TIMELINE~"] = "[U]",
    ["~INPUT_REPLAY_PREVIEW_AUDIO~"] = "[L]",
    ["~INPUT_VEH_DRIVE_LOOK~"] = "[Right Stick]",
    ["~INPUT_VEH_DRIVE_LOOK2~"] = "[Right Stick]",
    ["~INPUT_VEH_FLY_ATTACK2~"] = "[Right Mouse Button]",
    ["~INPUT_RADIO_WHEEL_UD~"] = "[Mouse Y]",
    ["~INPUT_RADIO_WHEEL_LR~"] = "[Mouse X]",
    ["~INPUT_VEH_SLOWMO_UD~"] = "[Mouse Y]",
    ["~INPUT_VEH_SLOWMO_UP_ONLY~"] = "[Mouse Y Up]",
    ["~INPUT_VEH_SLOWMO_DOWN_ONLY~"] = "[Mouse Y Down]",
    ["~INPUT_VEH_SLOWMO_LR~"] = "[Mouse X]",
    ["~INPUT_VEH_SLOWMO_LEFT_ONLY~"] = "[Mouse X Left]",
    ["~INPUT_VEH_SLOWMO_RIGHT_ONLY~"] = "[Mouse X Right]",
}

function ReplaceKeyString(text)
    if not string.find(text, "~.-~") then
        return text
    end

    for inputKey in string.gmatch(text, "~.-~") do
        local replacement = InputKeyStrings[inputKey]
        if replacement then
            text = text:gsub(inputKey, replacement)
        end
    end

    return text
end
