local isServer = IsDuplicityVersion()
if not isServer then
  return
end

ASSET_DEPLOYER_WATERMARK_PREFIX = ("-- This part is generated by sv-deployer.lua from %s"):format(GetCurrentResourceName())
ASSET_DEPLOYER_WATERMARK_SUFFIX = "-- Do not edit this part manually unless you know what you are doing"

local function trimContent(content)
  return content:strtrim()
end

local function insertAfterPattern(content, pattern, injection, suffix)
  content = trimContent(content)

  return content:gsub(pattern, function(match)
    return match .. "\n" .. injection .. (suffix or "\n")
  end)
end

function append(content, ...)
  return content .. table.concat({ ... }, "\n")
end

function loadFile(resourceName, filePath)
  return LoadResourceFile(resourceName, filePath)
end

function appendQB(content, injection)
  return insertAfterPattern(content, "QBShared.Items = {", injection, "\n")
end

function appendQBHospitalBeds(content, injection)
  return insertAfterPattern(content, "%['jailbeds'%] = {", injection, ",\n")
end

function appendQBConsumablesEat(content, injection)
  return insertAfterPattern(content, "eat = {", injection, ",\n")
end

function appendQBPhoneTarget(content, injection)
  return insertAfterPattern(content, "%(ContactData%.number%)", injection, "\n")
end

function appendQBJailEvent(content, injection)
  return insertAfterPattern(content, "%(playerId, time%)", injection, "\n")
end

function appendQBJailCommand(content)
  content = trimContent(content)
  return content:gsub("QBCore.Commands.Add%('jail'.-end%)", "")
end

function appendQBUnjailCommand(content)
  content = trimContent(content)
  return content:gsub("QBCore.Commands.Add%('unjail'.-end%)", "")
end

function appendQBConsumablesDrink(content, injection)
  return insertAfterPattern(content, "drink = {", injection, ",\n")
end

function appendAfterReturn(content, injection)
  return insertAfterPattern(content, "return {", injection, "\n")
end

function appendBasketBallHoops(content, injection)
  return insertAfterPattern(content, "BasketballHoops = {", injection, "\n")
end

function appendESXBasicNeedsAfterItems(content, injection)
  return insertAfterPattern(content, "Config.Items = {", injection, "\n")
end

function appendQBDoorLock(content, injection)
  return insertAfterPattern(content, "return {", injection, "\n")
end

function resolveDeploy(resourceName, deployEntries)
  if not isResourceLoaded(resourceName) then
    afprint("^1[%s]^7 Resource is not loaded.", Levels.ERROR, resourceName)
    return
  end

  afprint("^3[%s]^7 Deploying resource...", Levels.LOAD, resourceName)

  for deployName, deployData in pairs(deployEntries) do
    afprint("^3[%s:%s]^7 Processing...", Levels.LOAD, resourceName, deployName)

    if deployData.type == "file" then
      local fileContent = loadFile(resourceName, deployData.path)
      local processedContent = deployData.callback(fileContent, deployData.callbackData)

      if processedContent then
        SaveResourceFile(resourceName, deployData.path, processedContent, -1)
        afprint("^2[%s:%s]^7 Successfully saved to %s.", Levels.INFO, resourceName, deployName, deployData.path)
      else
        afprint("^1[%s:%s]^7 Deploy was not successful.", Levels.ERROR, resourceName, deployName)
      end
    elseif deployData.type == "basic" then
      local success, errorMessage = deployData.callback(deployData.callbackData)

      if not success then
        afprint("^1[%s:%s]^7 Deploy was not successful: %s", Levels.ERROR, resourceName, deployName, errorMessage)
      end
    elseif deployData.type == "copy-files" then
      local sourceFolder = deployData.source
      local targetFolder = deployData.target
      local filesToCopy = deployData.callback(deployData.callbackData)

      local currentResourcePath = GetResourcePath(GetCurrentResourceName())
      local targetResourcePath = GetResourcePath(resourceName)

      for _, fileName in ipairs(filesToCopy) do
        local sourcePath = string.format("%s/%s/%s", currentResourcePath, sourceFolder, fileName)
        local sourceFile = io.open(sourcePath, "rb")

        if sourceFile == nil then
          afprint(
            "^1[%s:%s]^7 Source file %s/%s does not exist in resource %s.",
            Levels.ERROR,
            resourceName,
            deployName,
            sourceFolder,
            fileName,
            GetCurrentResourceName()
          )
        else
          local fileData = sourceFile:read("*a")
          sourceFile:close()

          local targetPath = string.format("%s/%s/%s", targetResourcePath, targetFolder, fileName)
          local targetFile = io.open(targetPath, "wb")

          if targetFile == nil then
            afprint(
              "^1[%s:%s]^7 Target file %s/%s does not exist in resource %s.",
              Levels.ERROR,
              resourceName,
              deployName,
              targetFolder,
              fileName,
              resourceName
            )
          else
            targetFile:write(fileData)
            targetFile:close()

            afprint(
              "^2[%s:%s]^7 Successfully copied %s from %s to %s.",
              Levels.INFO,
              resourceName,
              deployName,
              fileName,
              string.format("%s/%s/", GetCurrentResourceName(), sourceFolder),
              string.format("%s/%s/", resourceName, targetFolder)
            )
          end
        end
      end
    end

    afprint("^2[%s:%s]^7 Successfully processed.", Levels.INFO, resourceName, deployName)
  end

  afprint("^2[%s]^7 Successfully deployed resource.", Levels.INFO, resourceName)
  return true
end

function createDeployer()
  local deployer = {
    deploys = {},
    deploysCache = {},
    command = nil,
    resetDeployCommand = nil,
    saveDeployInCache = false
  }

  function deployer.registerFileDeploy(self, deployName, resourceName, filePath, callback, callbackData)
    if not resourceName then
      return
    end

    if not self.deploys[resourceName] then
      self.deploys[resourceName] = {}
    end

    self.deploys[resourceName][deployName] = {
      type = "file",
      path = filePath,
      callback = callback,
      callbackData = callbackData or {}
    }
  end

  function deployer.registerDeploy(self, deployName, resourceName, callback, callbackData)
    if not self.deploys[resourceName] then
      self.deploys[resourceName] = {}
    end

    self.deploys[resourceName][deployName] = {
      type = "basic",
      callback = callback,
      callbackData = callbackData or {}
    }
  end

  function deployer.registerCopyFilesDeploy(self, deployName, resourceName, sourceFolder, targetFolder, callback, callbackData)
    if not self.deploys[resourceName] then
      self.deploys[resourceName] = {}
    end

    self.deploys[resourceName][deployName] = {
      type = "copy-files",
      source = sourceFolder,
      target = targetFolder,
      callback = callback,
      callbackData = callbackData or {}
    }
  end

  function deployer.deployResourceSpecific(self, resourceName, deployName)
    if self.saveDeployInCache and self:getDeployStateForResource(resourceName) then
      return afprint("^1[%s]^7 Resource is already deployed.", Levels.ERROR, resourceName)
    end

    return resolveDeploy(resourceName, {
      [deployName] = self.deploys[resourceName][deployName]
    })
  end

  function deployer.deployResource(self, resourceName)
    if self.saveDeployInCache and self:getDeployStateForResource(resourceName) then
      return afprint("^1[%s]^7 Resource is already deployed.", Levels.ERROR, resourceName)
    end

    return resolveDeploy(resourceName, self.deploys[resourceName])
  end

  function deployer.getDeployCacheNamePrefix(self, resourceName)
    if not resourceName then
      return nil
    end

    return ("%s_%s_%s"):format(GetCurrentResourceName(), "deployer", resourceName)
  end

  function deployer.getDeployStateForResource(self, resourceName)
    local isDeployed = false

    if resourceName then
      local kvpValue = GetResourceKvpInt(self:getDeployCacheNamePrefix(resourceName))
      if kvpValue == 1 then
        isDeployed = true
      end
    end

    return isDeployed
  end

  function deployer.setDeployStateIntoCache(self, resourceName, state)
    local kvpKey = self:getDeployCacheNamePrefix(resourceName)

    if kvpKey then
      SetResourceKvpInt(kvpKey, state)
    end

    if state == 1 then
      afprint("Resource ^3%s^7 deploy was successfully cached into KVP.", Levels.INFO, resourceName)
    elseif state == 0 then
      afprint(
        "Resource ^3%s^7 deploy was succesfully restarted, could be deployed again via command: (/%s %s)",
        Levels.LOAD,
        resourceName,
        self.command,
        resourceName
      )
    end
  end

  function deployer.deleteKvpByReourceName(self, resourceName)
    local kvpKey = self:getDeployCacheNamePrefix(resourceName)

    if kvpKey then
      SetResourceKvpInt(kvpKey, 0)
    end
  end

  function deployer.getDeployCache(self)
    local waitForCache = promise.new()

    if next(self.deploys) then
      local totalDeploys = table.len(self.deploys)
      local processedDeploys = 0

      for resourceName in pairs(self.deploys) do
        processedDeploys = processedDeploys + 1

        local deployState = self:getDeployStateForResource(resourceName)
        if deployState then
          self.deploysCache[resourceName] = {
            state = deployState,
            kvpKey = self:getDeployCacheNamePrefix(resourceName)
          }
        end

        if processedDeploys >= totalDeploys then
          waitForCache:resolve(true)
        end
      end
    else
      waitForCache:resolve(true)
    end

    Citizen.Await(waitForCache)

    if self.deploysCache and next(self.deploysCache) then
      afprint("Showing current cached resources into KVP storage!", Levels.LOAD)
      tprint(self.deploysCache)
    else
      afprint("The deployer KVP storage is empty!", Levels.INFO)
    end
  end

  function deployer.setSaveDeployInCache(self, enabled)
    self.saveDeployInCache = enabled
  end

  function deployer.registerResetDeployCommand(self, commandName)
    self.resetDeployCommand = commandName or "resetdeploy"

    RegisterCommand(commandName or "resetdeploy", function(source, args)
      if source ~= 0 then
        return
      end

      local resourceName = args[1]
      if resourceName == nil then
        afprint("Usage: /resetdeploy <resource> [name]", Levels.INFO)
        return
      end

      if not self.deploys[resourceName] then
        afprint("Resource named %s is not defined by us, some resource dont need it.", Levels.INFO, resourceName)
        return
      end

      if not self:getDeployStateForResource(resourceName) then
        afprint("Resource %s is not stored in KVP storage!", Levels.INFO, resourceName)
        return
      end

      self:setDeployStateIntoCache(resourceName, 0)
    end)
  end

  function deployer.registerDefaultCommand(self, commandName)
    self.command = commandName or "deploy"
    self.deployState = false

    RegisterCommand(commandName or "deploy", function(source, args)
      if source ~= 0 then
        return
      end

      local resourceName = args[1]
      if resourceName == nil then
        afprint("Usage: prisonsetup <resource> [name]", Levels.ERROR)
        return
      end

      if not self.deploys[resourceName] then
        print(string.format(
          "^3============================================================^7\n^3[Deployer Information]^7\n------------------------------------------------------------\n- Resource: ^5%s^7\n- This resource is ^3not registered as a deploy^7.\n- ✅ Nothing is wrong — deploys are only used for moving ^2inventory images/items^7 into your supported inventory.\n- 🔄 Integrations are handled automatically if the resource is supported in ^5config.lua^7.\n- 📋 See valid deploys listed below. Only those shown\n  (prisonsetup: xxx) can be used if needed.\n------------------------------------------------------------\n^3============================================================^7\n",
          resourceName
        ))

        self:suggestDeploys(true)
        return
      end

      local deployName = args[2]
      if deployName ~= nil then
        if not self.deploys[resourceName][deployName] then
          print(string.format(
            "^3============================================================^7\n^3[Deployer Information]^7\n------------------------------------------------------------\n- Resource: ^5%s^7\n- This resource is ^3not registered as a deploy^7.\n- ✅ Nothing is wrong — deploys are only used for moving ^2inventory images/items^7 into your supported inventory.\n- 🔄 Integrations are handled automatically if the resource is supported in ^5config.lua^7.\n- 📋 See valid deploys listed below. Only those shown\n  (prisonsetup: xxx) can be used if needed.\n------------------------------------------------------------\n^3============================================================^7\n",
            resourceName
          ))

          self:suggestDeploys(true)
          return
        end

        self.deployState = self:deployResourceSpecific(resourceName, deployName)
        return
      end

      self.deployState = self:deployResource(resourceName)

      if self.deployState and self.saveDeployInCache then
        self:setDeployStateIntoCache(resourceName, 1)
      end
    end)
  end

  function deployer.suggestDeploys(self, printSuggestions)
    local suggestions = {}
    local cachedSuggestions = {}

    if not next(self.deploys) then
      afprint("No deploys are registered yet.", Levels.INFO)
      return
    end

    for resourceName, deployList in pairs(self.deploys) do
      if isResourceLoaded(resourceName) then
        suggestions[resourceName] = {}
        cachedSuggestions[resourceName] = {}

        for deployName in pairs(deployList) do
          table.insert(suggestions[resourceName], deployName)

          if self.saveDeployInCache and self:getDeployStateForResource(resourceName) then
            table.insert(cachedSuggestions[resourceName], deployName)
          end
        end
      end
    end

    if printSuggestions then
      for resourceName, deployNames in pairs(suggestions) do
        local joinedNames = table.concat(deployNames, "^7,^3 ")

        if self.saveDeployInCache then
          if not self:getDeployStateForResource(resourceName) then
            afprint(
              "Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (%s %s)",
              Levels.LOAD,
              resourceName,
              table.size(deployNames),
              joinedNames,
              self.command,
              resourceName
            )
          end
        else
          afprint(
            "Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (%s %s)",
            Levels.LOAD,
            resourceName,
            table.size(deployNames),
            joinedNames,
            self.command,
            resourceName
          )
        end
      end
    end

    return suggestions
  end

  return deployer
end