-- =====================================================
--  rcore_police · modules/bridge/sv-deployer.lua
--  Engineered by Eazy Fxap
--  Original: 1065 lines → Cleaned: 370 lines
-- =====================================================

-- Server-side only
if not IsDuplicityVersion() then return end

-- ============================================================
--  WATERMARK
-- ============================================================

ASSET_DEPLOYER_WATERMARK_PREFIX = ("-- This part is generated by sv-deployer.lua from %s"):format(GetCurrentResourceName())
ASSET_DEPLOYER_WATERMARK_SUFFIX = "-- Do not edit this part manually unless you know what you are doing"

-- ============================================================
--  FILE HELPERS
-- ============================================================

-- Append a line to a string buffer
function append(buffer, ...)
    return buffer .. table.concat({...}, "\n")
end

-- Load a file from a resource
function loadFile(resourceName, filePath)
    return LoadResourceFile(resourceName, filePath)
end

-- ============================================================
--  APPEND HELPERS (inject content into existing resource files)
-- ============================================================

local function makeAppendHelper(pattern, suffix)
    return function(content, injection)
        content = content:strtrim()
        return content:gsub(pattern, function(match)
            return match .. "\n" .. injection .. suffix
        end)
    end
end

appendQB                  = makeAppendHelper("QBShared%.Items = {",               "\n")
appendQBHospitalBeds      = makeAppendHelper("%['jailbeds'%] = {",                 ",\n")
appendQBConsumablesEat    = makeAppendHelper("eat = {",                            ",\n")
appendQBPhoneTarget       = makeAppendHelper("%(ContactData%.number%)",            "\n")
appendQBJailEvent         = makeAppendHelper("%(playerId, time%)",                 "\n")
appendQBConsumablesDrink  = makeAppendHelper("drink = {",                          ",\n")
appendAfterReturn         = makeAppendHelper("return {",                           "\n")
appendBasketBallHoops     = makeAppendHelper("BasketballHoops = {",               "\n")
appendESXBasicNeedsAfterItems = makeAppendHelper("Config%.Items = {",             "\n")
appendQBDoorLock          = makeAppendHelper("return {",                           "\n")

function appendQBJailCommand(content)
    content = content:strtrim()
    return content:gsub("QBCore.Commands.Add%('jail'.-end%)", "")
end

function appendQBUnjailCommand(content)
    content = content:strtrim()
    return content:gsub("QBCore.Commands.Add%('unjail'.-end%)", "")
end

-- ============================================================
--  DEPLOY RESOLVER — Execute deploy actions for a resource
-- ============================================================

function resolveDeploy(resourceName, deployActions)
    if not isResourceLoaded(resourceName) then
        afprint("^1[%s]^7 Resource is not loaded.", Levels.ERROR, resourceName)
        return
    end

    afprint("^3[%s]^7 Deploying resource...", Levels.LOAD, resourceName)
    local selfResourcePath = GetResourcePath(GetCurrentResourceName())
    local targetResourcePath = GetResourcePath(resourceName)

    for actionName, action in pairs(deployActions) do
        afprint("^3[%s:%s]^7 Processing...", Levels.LOAD, resourceName, actionName)

        if action.type == "file" then
            -- Read file, transform it, then save
            local fileContent = loadFile(resourceName, action.path)
            local newContent  = action.callback(fileContent, action.callbackData)
            if newContent then
                SaveResourceFile(resourceName, action.path, newContent, -1)
                afprint("^2[%s:%s]^7 Successfully saved to %s.", Levels.INFO, resourceName, actionName, action.path)
            else
                afprint("^1[%s:%s]^7 Deploy was not successful.", Levels.ERROR, resourceName, actionName)
            end

        elseif action.type == "basic" then
            -- Run a basic callback
            local ok, errMsg = action.callback(action.callbackData)
            if not ok then
                afprint("^1[%s:%s]^7 Deploy was not successful: %s", Levels.ERROR, resourceName, actionName, errMsg)
            end

        elseif action.type == "copy-files" then
            -- Copy files from source dir in this resource to target dir in the target resource
            local fileList = action.callback(action.callbackData)
            for _, fileName in ipairs(fileList) do
                local srcPath = ("%s/%s/%s"):format(selfResourcePath, action.source, fileName)
                local srcFile = io.open(srcPath, "rb")
                if srcFile == nil then
                    afprint("^1[%s:%s]^7 Source file %s/%s does not exist in resource %s.",
                        Levels.ERROR, resourceName, actionName, action.source, fileName, GetCurrentResourceName())
                else
                    local srcContent = srcFile:read("*a")
                    srcFile:close()

                    local dstPath = ("%s/%s/%s"):format(targetResourcePath, action.target, fileName)
                    local dstFile = io.open(dstPath, "wb")
                    if dstFile == nil then
                        afprint("^1[%s:%s]^7 Target file %s/%s does not exist in resource %s.",
                            Levels.ERROR, resourceName, actionName, action.target, fileName, resourceName)
                    else
                        dstFile:write(srcContent)
                        dstFile:close()
                        afprint("^2[%s:%s]^7 Successfully copied %s from %s to %s.",
                            Levels.INFO, resourceName, actionName, fileName,
                            ("%s/%s/"):format(GetCurrentResourceName(), action.source),
                            ("%s/%s/"):format(resourceName, action.target))
                    end
                end
            end
        end

        afprint("^2[%s:%s]^7 Successfully processed.", Levels.INFO, resourceName, actionName)
    end

    afprint("^2[%s]^7 Successfully deployed resource.", Levels.INFO, resourceName)
    return true
end

-- ============================================================
--  DEPLOYER FACTORY — Creates a deployer instance
-- ============================================================

function createDeployer()
    local deployer = {
        deploys           = {},
        deploysCache      = {},
        command           = nil,
        resetDeployCommand = nil,
        saveDeployInCache = false,
    }

    -- Register a file-based deploy action
    function deployer:registerFileDeploy(actionName, resourceName, filePath, callback, callbackData)
        if not self.deploys[resourceName] then
            self.deploys[resourceName] = {}
        end
        self.deploys[resourceName][actionName] = {
            type         = "file",
            path         = filePath,
            callback     = callback,
            callbackData = callbackData or {},
        }
    end

    -- Register a basic callback deploy action
    function deployer:registerDeploy(actionName, resourceName, callback, callbackData)
        if not self.deploys[resourceName] then
            self.deploys[resourceName] = {}
        end
        self.deploys[resourceName][actionName] = {
            type         = "basic",
            callback     = callback,
            callbackData = callbackData or {},
        }
    end

    -- Register a copy-files deploy action
    function deployer:registerCopyFilesDeploy(actionName, resourceName, sourceDir, targetDir, callback, callbackData)
        if not self.deploys[resourceName] then
            self.deploys[resourceName] = {}
        end
        self.deploys[resourceName][actionName] = {
            type         = "copy-files",
            source       = sourceDir,
            target       = targetDir,
            callback     = callback,
            callbackData = callbackData or {},
        }
    end

    -- Get the KVP key prefix for a resource
    function deployer:getDeployCacheNamePrefix(resourceName)
        if not resourceName then return nil end
        return ("%s_%s_%s"):format(GetCurrentResourceName(), "deployer", resourceName)
    end

    -- Check if a resource has been deployed (via KVP)
    function deployer:getDeployStateForResource(resourceName)
        if not resourceName then return false end
        local kvpKey = self:getDeployCacheNamePrefix(resourceName)
        return GetResourceKvpInt(kvpKey) == 1
    end

    -- Store or clear deploy state in KVP
    function deployer:setDeployStateIntoCache(resourceName, state)
        local kvpKey = self:getDeployCacheNamePrefix(resourceName)
        if kvpKey then
            SetResourceKvpInt(kvpKey, state)
        end
        if state == 1 then
            afprint("Resource ^3%s^7 deploy was successfully cached into KVP.", Levels.INFO, resourceName)
        elseif state == 0 then
            afprint("Resource ^3%s^7 deploy was succesfully restarted, could be deployed again via command: (/%s %s)",
                Levels.LOAD, resourceName, self.command, resourceName)
        end
    end

    -- Reset KVP entry to 0
    function deployer:deleteKvpByReourceName(resourceName)
        local kvpKey = self:getDeployCacheNamePrefix(resourceName)
        if kvpKey then
            SetResourceKvpInt(kvpKey, 0)
        end
    end

    -- Deploy a specific named action for a resource
    function deployer:deployResourceSpecific(resourceName, actionName)
        if self.saveDeployInCache and self:getDeployStateForResource(resourceName) then
            return afprint("^1[%s]^7 Resource is already deployed.", Levels.ERROR, resourceName)
        end
        local actions = { [actionName] = self.deploys[resourceName][actionName] }
        return resolveDeploy(resourceName, actions)
    end

    -- Deploy all actions for a resource
    function deployer:deployResource(resourceName)
        if self.saveDeployInCache and self:getDeployStateForResource(resourceName) then
            return afprint("^1[%s]^7 Resource is already deployed.", Levels.ERROR, resourceName)
        end
        return resolveDeploy(resourceName, self.deploys[resourceName])
    end

    -- Scan all registered deploys and pre-cache their KVP states
    function deployer:getDeployCache()
        local p = promise.new()
        if next(self.deploys) then
            local total = table.len(self.deploys)
            local idx   = 0
            for resourceName in pairs(self.deploys) do
                idx = idx + 1
                if resourceName then
                    local state = self:getDeployStateForResource(resourceName)
                    if state then
                        self.deploysCache[resourceName] = {
                            state  = state,
                            kvpKey = self:getDeployCacheNamePrefix(resourceName),
                        }
                    end
                end
                if total <= idx then p:resolve(true) end
            end
        else
            p:resolve(true)
        end
        Citizen.Await(p)

        if self.deploysCache and next(self.deploysCache) then
            afprint("Showing current cached resources into KVP storage!", Levels.LOAD)
            tprint(self.deploysCache)
        else
            afprint("The deployer KVP storage is empty!", Levels.INFO)
        end
    end

    -- Set whether deploy state should be cached in KVP
    function deployer:setSaveDeployInCache(enabled)
        self.saveDeployInCache = enabled
    end

    -- Register a /resetdeploy <resource> command
    function deployer:registerResetDeployCommand(cmdName)
        local cmd = cmdName or "resetdeploy"
        self.resetDeployCommand = cmd
        RegisterCommand(cmd, function(source, args)
            if source ~= 0 then return end
            local resourceName = args[1]
            if not resourceName then
                afprint("Usage: /resetdeploy <resource>", Levels.ERROR)
                return
            end
            if not self.deploys[resourceName] then
                afprint("Resource %s is not registered yet.", Levels.ERROR, resourceName)
                return
            end
            if not self:getDeployStateForResource(resourceName) then
                afprint("Resource %s is not stored in KVP storage!", Levels.ERROR, resourceName)
                return
            end
            self:setDeployStateIntoCache(resourceName, 0)
        end)
    end

    -- Register /deploy <resource> [action] command
    function deployer:registerDefaultCommand(cmdName)
        local cmd = cmdName or "deploy"
        self.command    = cmd
        self.deployState = false

        local notRegisteredMsg = "^3============================================================^7\n^3[Deployer Information]^7\n------------------------------------------------------------\n- Resource: ^5%s^7\n- This resource is ^3not registered as a deploy^7.\n- ✅ Nothing is wrong — deploys are only used for moving ^2inventory images/items^7 into your supported inventory.\n- 📌 Integrations are handled automatically if the resource is supported in ^5config.lua^7.\n- 📋 See valid deploys listed below. Only those shown\n  (policesetup: xxx) can be used if needed.\n------------------------------------------------------------\n^3============================================================^7\n"

        RegisterCommand(cmd, function(source, args)
            if source ~= 0 then return end
            local resourceName = args[1]
            if not resourceName then
                afprint("Usage: /policesetup <resource> [name]", Levels.ERROR)
                return
            end

            if not self.deploys[resourceName] then
                print(notRegisteredMsg:format(resourceName))
                self:suggestDeploys(true)
                return
            end

            local actionName = args[2]
            if actionName ~= nil then
                if not self.deploys[resourceName][actionName] then
                    print(notRegisteredMsg:format(resourceName))
                    self:suggestDeploys(true)
                    return
                end
                self.deployState = self:deployResourceSpecific(resourceName, actionName)
                return
            end

            self.deployState = self:deployResource(resourceName)
            if self.deployState and self.saveDeployInCache then
                self:setDeployStateIntoCache(resourceName, 1)
            end
        end)
    end

    -- Suggest available deploys in console
    function deployer:suggestDeploys(verbose)
        local available = {}
        local cached    = {}

        if not next(self.deploys) then
            afprint("No deploys are registered yet.", Levels.INFO)
            return
        end

        for resourceName, actions in pairs(self.deploys) do
            if isResourceLoaded(resourceName) then
                available[resourceName] = {}
                cached[resourceName]    = {}
                for actionName in pairs(actions) do
                    table.insert(available[resourceName], actionName)
                    if self.saveDeployInCache and self:getDeployStateForResource(resourceName) then
                        table.insert(cached[resourceName], actionName)
                    end
                end
            end
        end

        if verbose then
            for resourceName, actionList in pairs(available) do
                local deployList = table.concat(actionList, "^7,^3 ")
                if self.saveDeployInCache then
                    if self:getDeployStateForResource(resourceName) then
                        afprint("Resource ^3%s^7 is already deployed. Deploy reset command ^3%s^7: ^3%s^7 (/%s %s)",
                            Levels.LOAD, resourceName, table.size(cached), deployList, self.resetDeployCommand, resourceName)
                    else
                        afprint("Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (/%s %s)",
                            Levels.LOAD, resourceName, table.size(actionList), deployList, self.command, resourceName)
                    end
                else
                    afprint("Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (/%s %s)",
                        Levels.LOAD, resourceName, table.size(actionList), deployList, self.command, resourceName)
                end
            end
        end

        return available
    end

    return deployer
end
